### ISSUE TITLE
Kommuner with no herbivores and negative reindeer densities

### ISSUE THREAD

**Issue by JamesDMSpeed** [JamesDMSpeed/Norway-large-herbivores#1]
Knr 1857 and 1874 have no herbivores at all in 2009 and 2015.
Knr 1841 has negative semi-domestic reindeer biomass in 1959 and 69.
These need to be checked

**Comment by gunnaraustrheim** [comment]
I'm on it. Have made a 'dummy script' for how to change the numbers. Now I just need to find out what the numbers should be.

**Comment by gunnaraustrheim** [comment]
Knr 1857 and 1874 have no herbivores at all in 2009 and 2015. This is checked for all individual herbivore species.

Knr 1841 has negative semi-domestic reindeer biomass in 1959 and 69. This should be changed to 0, due to norwegian reindeer grazed in Sweden as part of the bilateral agreement
